# Generated by Django 3.2.7 on 2021-12-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='Username',
            field=models.EmailField(max_length=256),
        ),
    ]
